version: '3'
services:
  springcloud-framework-vue:
    image:  harbor.yscredit.com/mujun-cloud/springcloud-framework-vue
    container_name: sc-vue
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    network_mode: "host"
    ports:
      - 8218:8218
